// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
var __defProp = Object.defineProperty;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __esm = (fn, res) => function __init() {
  return fn && (res = (0, fn[__getOwnPropNames(fn)[0]])(fn = 0)), res;
};
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};

// <define:import.meta.env>
var init_define_import_meta_env = __esm({
  "<define:import.meta.env>"() {
  }
});

// src/utils/jsonSchemaValidator.ts
var jsonSchemaValidator_exports = {};
__export(jsonSchemaValidator_exports, {
  formatValidationMessages: () => formatValidationMessages,
  validateMLResultsSchema: () => validateMLResultsSchema
});
function validateMLResultsSchema(data) {
  const errors = [];
  const warnings = [];
  if (!data || typeof data !== "object") {
    errors.push({
      field: "root",
      message: "Invalid JSON: Expected an object at the root level",
      severity: "error"
    });
    return { isValid: false, errors, warnings };
  }
  const obj = data;
  if (!obj.metadata) {
    errors.push({
      field: "metadata",
      message: "Missing required field 'metadata'. This should contain analysis configuration.",
      severity: "error"
    });
  } else {
    validateMetadata(obj.metadata, errors, warnings);
  }
  if (!obj.model_performance) {
    errors.push({
      field: "model_performance",
      message: "Missing required field 'model_performance'. This should contain performance metrics for each ML model.",
      severity: "error"
    });
  } else {
    validateModelPerformance(obj.model_performance, errors, warnings);
  }
  if (!obj.feature_importance) {
    warnings.push({
      field: "feature_importance",
      message: "Missing 'feature_importance' array. Feature importance charts will be empty.",
      severity: "warning"
    });
  } else if (!Array.isArray(obj.feature_importance)) {
    errors.push({
      field: "feature_importance",
      message: "'feature_importance' should be an array of objects with 'feature' and 'importance' fields.",
      severity: "error"
    });
  }
  if (!obj.selected_features) {
    warnings.push({
      field: "selected_features",
      message: "Missing 'selected_features' array. Selected features list will be empty.",
      severity: "warning"
    });
  } else if (!Array.isArray(obj.selected_features)) {
    errors.push({
      field: "selected_features",
      message: "'selected_features' should be an array of feature names.",
      severity: "error"
    });
  }
  if (obj.survival_analysis) {
    validateSurvivalAnalysis(obj.survival_analysis, errors, warnings);
  }
  if (obj.profile_ranking) {
    validateProfileRanking(obj.profile_ranking, errors, warnings);
  }
  if (obj.preprocessing) {
    validatePreprocessing(obj.preprocessing, errors, warnings);
  }
  return {
    isValid: errors.length === 0,
    errors,
    warnings
  };
}
function validateMetadata(metadata, errors, warnings) {
  if (typeof metadata !== "object" || metadata === null) {
    errors.push({
      field: "metadata",
      message: "'metadata' should be an object containing configuration details.",
      severity: "error"
    });
    return;
  }
  const meta = metadata;
  if (!meta.config) {
    errors.push({
      field: "metadata.config",
      message: "Missing 'metadata.config'. This should contain analysis parameters like target_variable, n_folds, etc.",
      severity: "error"
    });
  } else {
    const config = meta.config;
    if (!config.target_variable) {
      warnings.push({
        field: "metadata.config.target_variable",
        message: "Missing 'target_variable'. Unable to display which variable was used for classification.",
        severity: "warning"
      });
    }
  }
  if (!meta.r_version) {
    warnings.push({
      field: "metadata.r_version",
      message: "Missing 'r_version'. R version information will not be displayed.",
      severity: "warning"
    });
  }
  if (!meta.generated_at) {
    warnings.push({
      field: "metadata.generated_at",
      message: "Missing 'generated_at'. Analysis timestamp will not be displayed.",
      severity: "warning"
    });
  }
}
function validateModelPerformance(perf, errors, warnings) {
  if (typeof perf !== "object" || perf === null) {
    errors.push({
      field: "model_performance",
      message: "'model_performance' should be an object with model names as keys (rf, svm, xgboost, etc.).",
      severity: "error"
    });
    return;
  }
  const models = perf;
  const validModels = ["rf", "svm", "xgboost", "knn", "mlp", "hard_vote", "soft_vote"];
  const foundModels = Object.keys(models).filter((k) => validModels.includes(k));
  if (foundModels.length === 0) {
    errors.push({
      field: "model_performance",
      message: "No valid models found. Expected at least one of: rf, svm, xgboost, knn, mlp, hard_vote, soft_vote.",
      severity: "error"
    });
  }
  foundModels.forEach((modelName) => {
    const modelData = models[modelName];
    if (!modelData.auroc && !modelData.accuracy) {
      warnings.push({
        field: `model_performance.${modelName}`,
        message: `Model '${modelName}' is missing both 'auroc' and 'accuracy' metrics.`,
        severity: "warning"
      });
    }
  });
}
function validateSurvivalAnalysis(survival, errors, warnings) {
  if (typeof survival !== "object" || survival === null) {
    warnings.push({
      field: "survival_analysis",
      message: "'survival_analysis' should be an object. Survival analysis tab will be empty.",
      severity: "warning"
    });
    return;
  }
  const surv = survival;
  if (!surv.time_variable) {
    warnings.push({
      field: "survival_analysis.time_variable",
      message: "Missing 'time_variable'. Should specify the survival time column name.",
      severity: "warning"
    });
  }
  if (!surv.event_variable) {
    warnings.push({
      field: "survival_analysis.event_variable",
      message: "Missing 'event_variable'. Should specify the event/censoring column name.",
      severity: "warning"
    });
  }
  if (surv.per_gene) {
    const perGene = surv.per_gene;
    if (Array.isArray(perGene)) {
      if (perGene.length === 0) {
        warnings.push({
          field: "survival_analysis.per_gene",
          message: "'per_gene' array is empty. No gene-level survival statistics will be shown.",
          severity: "warning"
        });
      } else {
        const first = perGene[0];
        if (!first.gene) {
          errors.push({
            field: "survival_analysis.per_gene[0].gene",
            message: "Per-gene survival entries must have a 'gene' field with the gene name.",
            severity: "error"
          });
        }
        validateSurvivalStats(first, "survival_analysis.per_gene[0]", warnings);
      }
    } else if (typeof perGene === "object" && perGene !== null) {
      const geneKeys = Object.keys(perGene);
      if (geneKeys.length === 0) {
        warnings.push({
          field: "survival_analysis.per_gene",
          message: "'per_gene' object is empty. No gene-level survival statistics will be shown.",
          severity: "warning"
        });
      } else {
        const first = perGene[geneKeys[0]];
        if (first && !first.gene) {
          warnings.push({
            field: `survival_analysis.per_gene.${geneKeys[0]}.gene`,
            message: "Per-gene survival entries should have a 'gene' field. Will try to use object key as gene name.",
            severity: "warning"
          });
        }
        if (first) {
          validateSurvivalStats(first, `survival_analysis.per_gene.${geneKeys[0]}`, warnings);
        }
      }
    } else {
      warnings.push({
        field: "survival_analysis.per_gene",
        message: "'per_gene' should be an array or object of gene survival statistics.",
        severity: "warning"
      });
    }
  } else {
    warnings.push({
      field: "survival_analysis.per_gene",
      message: "Missing 'per_gene'. Gene-level survival analysis will not be shown.",
      severity: "warning"
    });
  }
  if (surv.model_risk_scores) {
    const modelRisk = surv.model_risk_scores;
    if (!Array.isArray(modelRisk) && (typeof modelRisk !== "object" || modelRisk === null)) {
      warnings.push({
        field: "survival_analysis.model_risk_scores",
        message: "'model_risk_scores' should be an array or object. Model risk survival tab will be hidden.",
        severity: "warning"
      });
    }
  }
}
function validateSurvivalStats(obj, path, warnings) {
  const requiredStats = ["logrank_p", "cox_hr", "cox_p"];
  requiredStats.forEach((stat) => {
    if (obj[stat] === void 0 || obj[stat] === null) {
      warnings.push({
        field: `${path}.${stat}`,
        message: `Missing '${stat}'. This survival statistic will show as 'NA'.`,
        severity: "warning"
      });
    }
  });
}
function validateProfileRanking(ranking, errors, warnings) {
  if (typeof ranking !== "object" || ranking === null) {
    warnings.push({
      field: "profile_ranking",
      message: "'profile_ranking' should be an object with 'top_profiles' and 'all_rankings' arrays.",
      severity: "warning"
    });
    return;
  }
  const rank = ranking;
  if (!rank.top_profiles && !rank.all_rankings) {
    warnings.push({
      field: "profile_ranking",
      message: "Missing both 'top_profiles' and 'all_rankings'. Profile ranking table will be empty.",
      severity: "warning"
    });
  }
  if (rank.all_rankings && Array.isArray(rank.all_rankings) && rank.all_rankings.length > 0) {
    const first = rank.all_rankings[0];
    if (!first.sample_id && first.sample_index === void 0) {
      warnings.push({
        field: "profile_ranking.all_rankings[0]",
        message: "Profile entries should have 'sample_id' or 'sample_index' for identification.",
        severity: "warning"
      });
    }
  }
}
function validatePreprocessing(prep, errors, warnings) {
  if (typeof prep !== "object" || prep === null) {
    warnings.push({
      field: "preprocessing",
      message: "'preprocessing' should be an object with data statistics.",
      severity: "warning"
    });
    return;
  }
  const p = prep;
  if (p.class_distribution) {
    if (Array.isArray(p.class_distribution)) {
      warnings.push({
        field: "preprocessing.class_distribution",
        message: `'class_distribution' is an array but should be an object with class names as keys and counts as values (e.g., {"Class_A": 50, "Class_B": 30}).`,
        severity: "warning"
      });
    }
  }
}
function formatValidationMessages(result) {
  const messages = [];
  if (result.errors.length > 0) {
    messages.push("\u274C ERRORS (must fix):");
    result.errors.forEach((e) => {
      messages.push(`  \u2022 ${e.field}: ${e.message}`);
    });
  }
  if (result.warnings.length > 0) {
    if (messages.length > 0) messages.push("");
    messages.push("\u26A0\uFE0F WARNINGS (may affect display):");
    result.warnings.forEach((w) => {
      messages.push(`  \u2022 ${w.field}: ${w.message}`);
    });
  }
  return messages;
}
var init_jsonSchemaValidator = __esm({
  "src/utils/jsonSchemaValidator.ts"() {
    init_define_import_meta_env();
  }
});

// lovable-mcp-supabase-entry.ts
init_define_import_meta_env();

// src/lib/mcp/index.ts
init_define_import_meta_env();
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/validate-json.ts
init_define_import_meta_env();
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^4.4.3";
var validate_json_default = defineTool({
  name: "validate_ml_results_json",
  title: "Validate ML results JSON",
  description: "Validate a multi-ML-classifier results JSON payload against the dashboard's expected schema. Returns whether it is valid plus any errors and warnings by field.",
  inputSchema: {
    json: z.string().min(1).describe("Full ML results JSON as a string. Must parse as a JSON object.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ json }) => {
    const { validateMLResultsSchema: validateMLResultsSchema2, formatValidationMessages: formatValidationMessages2 } = await Promise.resolve().then(() => (init_jsonSchemaValidator(), jsonSchemaValidator_exports));
    let parsed;
    try {
      parsed = JSON.parse(json);
    } catch (e) {
      return {
        content: [{ type: "text", text: `Invalid JSON: ${e.message}` }],
        isError: true
      };
    }
    const result = validateMLResultsSchema2(parsed);
    const text = [
      result.isValid ? "\u2705 Valid ML results JSON" : "\u274C Invalid ML results JSON",
      "",
      ...formatValidationMessages2(result)
    ].join("\n");
    return {
      content: [{ type: "text", text }],
      structuredContent: {
        isValid: result.isValid,
        errors: result.errors,
        warnings: result.warnings
      }
    };
  }
});

// src/lib/mcp/tools/summarize-run.ts
init_define_import_meta_env();
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z2 } from "npm:zod@^4.4.3";
function num(v) {
  return typeof v === "number" && Number.isFinite(v) ? v : null;
}
function fmt(n) {
  return n === null ? "n/a" : n.toFixed(4);
}
var summarize_run_default = defineTool2({
  name: "summarize_ml_run",
  title: "Summarize ML run",
  description: "Summarize a multi-ML-classifier results JSON: run metadata, preprocessing stats, per-model mean AUROC/accuracy/F1, top-N selected features, and best model.",
  inputSchema: {
    json: z2.string().min(1).describe("Full ML results JSON as a string."),
    top_features: z2.number().int().min(1).max(200).optional().describe("How many top selected features to include (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ json, top_features }) => {
    let data;
    try {
      data = JSON.parse(json);
    } catch (e) {
      return {
        content: [{ type: "text", text: `Invalid JSON: ${e.message}` }],
        isError: true
      };
    }
    const topN = top_features ?? 20;
    const meta = data.metadata ?? {};
    const cfg = meta.config ?? {};
    const prep = data.preprocessing ?? {};
    const perf = data.model_performance ?? {};
    const features = Array.isArray(data.selected_features) ? data.selected_features : [];
    const modelRows = [];
    for (const [name, m] of Object.entries(perf)) {
      const mm = m ?? {};
      modelRows.push({
        model: name,
        auroc: num((mm.auroc ?? {}).mean),
        accuracy: num((mm.accuracy ?? {}).mean),
        f1: num((mm.f1_score ?? {}).mean),
        sensitivity: num((mm.sensitivity ?? {}).mean),
        specificity: num((mm.specificity ?? {}).mean)
      });
    }
    const bestByAuroc = modelRows.filter((r) => r.auroc !== null).sort((a, b) => (b.auroc ?? -1) - (a.auroc ?? -1))[0];
    const lines = [];
    lines.push(`# ML Run Summary`);
    lines.push(`- Generated: ${meta.generated_at ?? "n/a"}`);
    lines.push(`- R version: ${meta.r_version ?? "n/a"}`);
    lines.push(`- Target variable: ${cfg.target_variable ?? "n/a"}`);
    lines.push(
      `- Mode: ${cfg.analysis_mode ?? (prep.full_training_mode ? "full_training" : "cv")}`
    );
    if (cfg.n_folds || cfg.n_repeats) {
      lines.push(`- CV: ${cfg.n_folds ?? "?"} folds \xD7 ${cfg.n_repeats ?? "?"} repeats`);
    }
    if (cfg.train_ratio !== void 0) lines.push(`- Train ratio: ${cfg.train_ratio}`);
    lines.push(`- Feature selection: ${cfg.feature_selection_method ?? "n/a"} (max ${cfg.max_features ?? "n/a"})`);
    lines.push("");
    lines.push(`## Preprocessing`);
    lines.push(`- Samples: ${prep.original_samples ?? "n/a"}`);
    lines.push(`- Features: ${prep.original_features ?? "n/a"}`);
    lines.push(`- Missing: ${prep.missing_values ?? "n/a"} (${prep.missing_pct ?? "n/a"}%)`);
    lines.push(`- Class distribution: ${JSON.stringify(prep.class_distribution ?? {})}`);
    lines.push("");
    lines.push(`## Model Performance (mean)`);
    lines.push(`| Model | AUROC | Accuracy | F1 | Sens | Spec |`);
    lines.push(`|---|---|---|---|---|---|`);
    for (const r of modelRows) {
      lines.push(
        `| ${r.model} | ${fmt(r.auroc)} | ${fmt(r.accuracy)} | ${fmt(r.f1)} | ${fmt(r.sensitivity)} | ${fmt(r.specificity)} |`
      );
    }
    lines.push("");
    if (bestByAuroc) {
      lines.push(`**Best model by AUROC:** ${bestByAuroc.model} (${fmt(bestByAuroc.auroc)})`);
    }
    lines.push("");
    lines.push(`## Top ${Math.min(topN, features.length)} selected features`);
    lines.push(features.slice(0, topN).map((f, i) => `${i + 1}. ${f}`).join("\n") || "(none)");
    return {
      content: [{ type: "text", text: lines.join("\n") }],
      structuredContent: {
        metadata: meta,
        preprocessing: prep,
        models: modelRows,
        best_model_by_auroc: bestByAuroc ?? null,
        selected_features_top: features.slice(0, topN),
        selected_features_count: features.length
      }
    };
  }
});

// src/lib/mcp/tools/compare-runs.ts
init_define_import_meta_env();
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z3 } from "npm:zod@^4.4.3";
function num2(v) {
  return typeof v === "number" && Number.isFinite(v) ? v : null;
}
function fmt2(n) {
  return n === null ? "n/a" : n.toFixed(4);
}
function diff(a, b) {
  if (a === null || b === null) return "n/a";
  const d = b - a;
  const sign = d > 0 ? "+" : "";
  return `${sign}${d.toFixed(4)}`;
}
function extractModels(data) {
  const perf = data.model_performance ?? {};
  const out = {};
  for (const [name, m] of Object.entries(perf)) {
    const mm = m ?? {};
    out[name] = {
      auroc: num2((mm.auroc ?? {}).mean),
      accuracy: num2((mm.accuracy ?? {}).mean),
      f1: num2((mm.f1_score ?? {}).mean)
    };
  }
  return out;
}
var compare_runs_default = defineTool3({
  name: "compare_ml_runs",
  title: "Compare two ML runs",
  description: "Compare two multi-ML-classifier results JSON payloads (run A vs run B). Reports per-model metric deltas (AUROC/Accuracy/F1) and selected-feature overlap.",
  inputSchema: {
    json_a: z3.string().min(1).describe("Run A: full ML results JSON as a string."),
    json_b: z3.string().min(1).describe("Run B: full ML results JSON as a string."),
    label_a: z3.string().optional().describe("Optional label for run A (default 'A')."),
    label_b: z3.string().optional().describe("Optional label for run B (default 'B').")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ json_a, json_b, label_a, label_b }) => {
    let a;
    let b;
    try {
      a = JSON.parse(json_a);
      b = JSON.parse(json_b);
    } catch (e) {
      return {
        content: [{ type: "text", text: `Invalid JSON: ${e.message}` }],
        isError: true
      };
    }
    const A = label_a ?? "A";
    const B = label_b ?? "B";
    const ma = extractModels(a);
    const mb = extractModels(b);
    const modelNames = Array.from(/* @__PURE__ */ new Set([...Object.keys(ma), ...Object.keys(mb)])).sort();
    const featA = new Set(Array.isArray(a.selected_features) ? a.selected_features : []);
    const featB = new Set(Array.isArray(b.selected_features) ? b.selected_features : []);
    const intersection = [...featA].filter((f) => featB.has(f));
    const onlyA = [...featA].filter((f) => !featB.has(f));
    const onlyB = [...featB].filter((f) => !featA.has(f));
    const union = /* @__PURE__ */ new Set([...featA, ...featB]);
    const jaccard = union.size === 0 ? null : intersection.length / union.size;
    const lines = [];
    lines.push(`# Run comparison: ${A} vs ${B}`);
    lines.push("");
    lines.push(`## Model performance (mean AUROC / Accuracy / F1)`);
    lines.push(`| Model | ${A} AUROC | ${B} AUROC | \u0394 AUROC | ${A} Acc | ${B} Acc | \u0394 Acc | ${A} F1 | ${B} F1 | \u0394 F1 |`);
    lines.push(`|---|---|---|---|---|---|---|---|---|---|`);
    for (const name of modelNames) {
      const x = ma[name] ?? { auroc: null, accuracy: null, f1: null };
      const y = mb[name] ?? { auroc: null, accuracy: null, f1: null };
      lines.push(
        `| ${name} | ${fmt2(x.auroc)} | ${fmt2(y.auroc)} | ${diff(x.auroc, y.auroc)} | ${fmt2(x.accuracy)} | ${fmt2(y.accuracy)} | ${diff(x.accuracy, y.accuracy)} | ${fmt2(x.f1)} | ${fmt2(y.f1)} | ${diff(x.f1, y.f1)} |`
      );
    }
    lines.push("");
    lines.push(`## Selected feature overlap`);
    lines.push(`- ${A} features: ${featA.size}`);
    lines.push(`- ${B} features: ${featB.size}`);
    lines.push(`- Shared: ${intersection.length}`);
    lines.push(`- Only in ${A}: ${onlyA.length}`);
    lines.push(`- Only in ${B}: ${onlyB.length}`);
    lines.push(`- Jaccard: ${jaccard === null ? "n/a" : jaccard.toFixed(4)}`);
    return {
      content: [{ type: "text", text: lines.join("\n") }],
      structuredContent: {
        labels: { a: A, b: B },
        models: modelNames.map((name) => ({
          model: name,
          a: ma[name] ?? null,
          b: mb[name] ?? null
        })),
        features: {
          a_count: featA.size,
          b_count: featB.size,
          shared: intersection,
          only_a: onlyA,
          only_b: onlyB,
          jaccard
        }
      }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "multi-ml-classifier-mcp",
  title: "Multi-ML Classifier MCP",
  version: "0.1.0",
  instructions: "Stateless helpers for multi-ML-classifier results JSON files exported by the R pipeline. Use `validate_ml_results_json` to check a payload against the dashboard schema, `summarize_ml_run` to get run metadata + per-model AUROC/Accuracy/F1 + top selected features, and `compare_ml_runs` to diff two runs.",
  tools: [validate_json_default, summarize_run_default, compare_runs_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
